// <auto-generated />
using Best_web_application_ever.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Best_web_application_ever.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230807144853_migration_01")]
    partial class migration_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Best_web_application_ever.Model.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 37,
                            Name = "Tosaadsm"
                        },
                        new
                        {
                            Id = 2,
                            Age = 41,
                            Name = "Boasdasdb"
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            Name = "Sadsadm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
